[package]
name = "vm-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
snafu = "0.8.6"
vm = { path = "../vm" }
